name: Build/release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}
    permissions: write-all

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 23

      - name: Install dependencies
        run: npm install

      - name: Build and Publish Electron App
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Required for publishing to GitHub Releases
        run: npm run publish
